### ISSUE TITLE
Publish package to npm

### ISSUE THREAD

**Issue by ccapndave** [CliffCloud/Leaflet.EasyButton#16]
It would be cool to use this with an npm/browserify stack instead of just bower.

**Comment by atstp** [comment]
It's registered with npm under `leaflet-easybutton`, but i'm still sussing out the best way to make it available as a module. 

Have you seen/used any leaflet plugin modules out there? (i've only seen leaflet-pip)

At the moment, if you throw it straight from the package to the window, it be okay.  That's not great though; it'll be browserifyable by the end of the week.

**Comment by DecSander** [comment]
Just as a heads up to anybody else trying to use easybutton with browserify/npm who comes across this, you need to `npm install font-awesome' and make sure you link to the css for both easybutton and font-awesome in your html, otherwise it won't work.

**Comment by atstp** [comment]
ah, that's a good thing to mention.  I'll make sure it's a little more obvious!
