### ISSUE TITLE
Feature Request: Button change symbol

### ISSUE THREAD

**Issue by tforward** [CliffCloud/Leaflet.EasyButton#17]
As a user when a button is clicked the symbol of that button changes. Same would apply to to the tooltip text.

**Comment by atstp** [comment]
I like it!  

In the meantime, you can do that manually with the id option in [v1](https://github.com/CliffCloud/Leaflet.EasyButton/tree/v1)'s args

**Comment by atstp** [comment]
It's all set up over in [v1](https://github.com/CliffCloud/Leaflet.EasyButton/tree/v1-dev)!

[Here's](http://danielmontague.com/projects/easyButton.js/v1/examples/#changing-states) an example for it.

**Comment by tforward** [comment]
Awesome! Only other suggestion is to set a default state to the button. The link to the example you gave, the "Add Markers" button is blank during first load and does not change until it is pressed. It should have the "Add Markers" right from the first load.

**Comment by atstp** [comment]
Ah good eyes. turns out that brought out two bugs. 

Buttons should be initializing properly now. Let me know if something doesn't line up.

**Comment by tforward** [comment]
Looks good now! The only other thing that strikes me is the "In the
Functions" one. The "1" button disappears after being clicked. Maybe some
more documentation here would help / example.
