### ISSUE TITLE
UI: Button Dash Selection is persistent

### ISSUE THREAD

**Issue by tforward** [CliffCloud/Leaflet.EasyButton#18]
As a user when I click an easyButton button, a smaller dash line representing that it's being hovered over appears over the icon. However even after the button is clicked the dashed line remains and only disappears when user clicks somewhere else on screen.

Default buttons within Leaflet don't have this issue.

**Comment by atstp** [comment]
Is this in the current master or v1?

**Comment by tforward** [comment]
@atstp master version using firefox

I was able to fix it on my end by doing this, however something within easybutton would be better.

$(".leaflet-bar-part").mouseup(function(){
    $(this).blur();
})

**Comment by atstp** [comment]
Great, it's fixed! thanks!
