### ISSUE TITLE
example how to disable and enable button

### ISSUE THREAD

**Issue by hmarina** [CliffCloud/Leaflet.EasyButton#19]
Hello every one, how enable and disable a button, any example.

Thank you

**Comment by atstp** [comment]
@hmarina, are you using v0 or v1?

**Comment by hmarina** [comment]
v1

**Comment by atstp** [comment]
ah nice!

this should do the trick (add this to the html document you're using)
```
<style>
.leaflet-control.disabled{
  opacity:.5;
  pointer-events: none;
}
</style>
```
then call
```
yourEasyButton.disable()
```
Let me know if you have any other questions.

adding the styles inline was a bit too invasive, and those four lines weren't quite enough to warrant an extra stylesheet.  It's worth looking into more though; thanks for bringing it up!

**Comment by hmarina** [comment]
Thank you so much.

**Comment by hmarina** [comment]
Hello any question how enable and disable a button, any example in v0, it was more easy for me.

Thank you againt.

**Comment by atstp** [comment]
this one's a bit messier, the simplest way is after you've called

    yourEasyButton.addTo(yourMap);

call 

    yourEasyButton.removeFrom(yourMap);

then it will be more gone than disabled.

does this do what you want?

**Comment by hmarina** [comment]
Is there a way by style, I prefer this.
<style>
..
</style>


Thank you

**Comment by atstp** [comment]
thanks for opening another issue for v0. It's answered over on #20
