### ISSUE TITLE
how enable and disable a button, any example in v0

### ISSUE THREAD

**Issue by hmarina** [CliffCloud/Leaflet.EasyButton#20]
Hello any question how enable and disable a button, any example in v0, it is more easy for me.

Thank you againt.

**Comment by atstp** [comment]
there's not a great way to do this. but add these lines to your js
```
L.Control.EasyButtons.prototype.disable = function(){ L.DomUtil.addClass(this._container, 'disabled')};
L.Control.EasyButtons.prototype.enable = function(){ L.DomUtil.removeClass(this._container, 'disabled')};
```

and this to your css
```
.leaflet-control.disabled{
  opacity: .5;
  pointer-events: none;
}
```

then your v0 easyButtons will have `disable` and `enable` methods.

**Comment by hmarina** [comment]
You are the best, thank you

**Comment by hmarina** [comment]
When you say add this to you js, is in my personal js or in easy-button.js
How I should call the function, I tried L.Control.EasyButtons.prototype.disable(); and doesn't work

**Comment by atstp** [comment]
Personally, I'd append the two lines to `easy-button.js`. Can you do that?

Then you can do this:
```
var buttonInstance = L.easyButton(/* whatever arguments */);

buttonInstance.addTo(map);

buttonInstance.disable();
```

extra info:
> the two lines I posted "extend the prototype", which is just fancy-talk for saying that they
> make it possible on every easyButton.  prototypes aren't the friendliest part of js; 
> don't worry about understanding them. Even Leaflet goes to significant lengths to hide them.

**Comment by atstp** [comment]
@hmarina are things working for you?
