### ISSUE TITLE
Animated Toggle Issue

### ISSUE THREAD

**Issue by tforward** [CliffCloud/Leaflet.EasyButton#21]
I noticed this on the Animated Toggle button example however it may apply to others as well just I have not checked.

http://danielmontague.com/projects/easyButton.js/v1/examples/#animated-toggle

As a user, when I click the Animated Toggle button in rapid succession the map also zooms in (By default the map zooms in on a double click event) It should not do this when clicking the button. 

You need to have a function something like:

If cursor.onHover on animatedToggleButton:
        disable.map.doubleclickToZoom;

**Comment by atstp** [comment]
just fixed it, thanks!
