### ISSUE TITLE
Change state

### ISSUE THREAD

**Issue by n0ne** [CliffCloud/Leaflet.EasyButton#22]
Hi.
Tell me, please, have any the possibilities to change the state of the button, without pressing the button? for example, I have a single-page application, and when I click on the "Home" link, the button state must be changed to default

**Comment by atstp** [comment]
Yeah, for sure.  First, make sure you're using [v1](https://github.com/CliffCloud/Leaflet.EasyButton/tree/v1-dev) &mdash; you probably know that, but i'll be verbose for anyone else who sees this.

With v1, you'll define your button like this:
```
/*
 * because you'll need the button later,
 * attaching it to the window will make sure any 
 * spa scoping doesn't get in the way
 */
window.buttonWithHomeState = L.easyButton({  
  states: [{
    stateName: 'home',   // this is the name of the button's state
    icon: 'fa-home',
    title: 'add random markers',
    onClick: function(btn) {
      btn.state('other-not-home-state')
    }
  }, {
    stateName: 'other-not-home-state',
    icon: 'fa-question-circle',
    onClick: function() {
      // do something else
    },
    title: 'remove markers'
  }]
});
```

and from anywhere (probably click listener or home-nav hook), you'll be able to:
```
window.buttonWithHomeState.state('home');  // go a specific state by name
```

Good luck! Let me know how this works out, if there's trouble, let me know which spa framework you're using and i'll send something more specific to that.
