### ISSUE TITLE
Version numbers on bower

### ISSUE THREAD

**Issue by MarkAPhillips** [CliffCloud/Leaflet.EasyButton#23]
when I check version on bower using

```
bower list
```

it returns the following

```
L.EasyButton#bd1dd296cc
```

I would expect 

```
L.EasyButton#0.0.1
```

Looking at the releases I see you have tagged a version v0 - Can I suggest you create another release i.e. v0.0.1 which follows the semantic versioning supported by bower.

**Comment by MarkAPhillips** [comment]
Also for consistency sakes would it better to rename the package - leaflet.easybutton to bring it inline with other leaflet plugins - rather than L.EasyButton - it would make it easier to find on bower also - just a suggestion

**Comment by atstp** [comment]
Thanks for bringing this up.  It should all be in order now, and per your suggestion I unregistered `L.EasyButton`; it's now under `Leaflet.EasyButton` with proper versioning.  

```
$ bower info Leaflet.EasyButton
bower Leaflet.EasyButton#*      cached git://github.com/CliffCloud/Leaflet.EasyButton.git#1.0.0
bower Leaflet.EasyButton#*    validate 1.0.0 against git://github.com/CliffCloud/Leaflet.EasyButton.git#*

{
  name: 'Leaflet.EasyButton',
  homepage: 'https://github.com/CliffCloud/Leaflet.EasyButtons',
  authors: [
    'atstp <dan.ll.montague@gmail.com>'
  ],
  description: 'Easily add Font Awesome control buttons to Leaflet maps with attached callbacks',
  main: [
    'src/easy-button.js',
    'src/easy-button.css'
  ],
  keywords: [
    'Leaflet',
    'map',
    'button'
  ],
  license: 'MIT',
  ignore: [
    '**/.*',
    'node_modules',
    'bower_components',
    'test',
    'tests'
  ],
  version: '1.0.0'
}

Available versions:
  - 1.0.0
  - 0.0.2
  - 0.0.1
```
