### ISSUE TITLE
Location of source files moved when installing from bower 

### ISSUE THREAD

**Issue by MarkAPhillips** [CliffCloud/Leaflet.EasyButton#24]
Relates to my previous question it seems at some point the source css and js files were moved to the

```
src
```

directory - and no release was made with these changes.

My build failed as it could no longer find these files as they have moved.

In the future would it possible to tag any changes (especially breaking)  as a new release v0.0.2 (or theoretically v0.1.0)

Thanks

**Comment by atstp** [comment]
Its fixed (as you saw in the other issue), but likely broken again with the package rename (now `Leaflet.EasyButton`).  

 If anything else comes up, let me know; I'll be checking in more frequently for the next few days.  Sorry for the breaking changes!
