### ISSUE TITLE
Package Leaflet.EasyButton not found

### ISSUE THREAD

**Issue by MarkAPhillips** [CliffCloud/Leaflet.EasyButton#25]
```
> bower install Leaflet.Easybutton --save-dev
bower cached        git://github.com/CliffCloud/Leaflet.EasyButton.git#1.0.0
bower validate      1.0.0 against git://github.com/CliffCloud/Leaflet.EasyButton.git#1.0.0
bower ENOTFOUND     Package Leaflet.Easybutton not found

```
 It seems I can still install L.EasyButton though. When I manually add Leaflet.Easybutton to my bower.json file and 

```
bower list
```

I get the following:

```
├── L.EasyButton#1.0.0 extraneous
├── Leaflet.EasyButton not installed
```
 Maybe there is a naming issue or registration issue 

as would suggest that it is all lower case e.g.

```
leaflet.easybutton
```

see https://github.com/bower/bower.json-spec#name for naming conventions for packages

**Comment by MarkAPhillips** [comment]
OK this might have been a caching issue but it might be worth looking at the naming convention as seems to work now - thanks!

**Comment by MarkAPhillips** [comment]
Definitely some issue as seems there is still some reference to L.EasyButton somewhere in bower 

Also maybe the folder that it deploys into should be leaflet.easybutton

looking at the .bower.json file there is 

```
"_originalSource": "L.EasyButton"
```

which may be the issue

**Comment by atstp** [comment]
I've got a hunch that might be to protect package publishers from breaking other people's builds with package renames, in the same way that 

https://github.com/CliffCloud/Leaflet.EasyButtons (when the repo was first published, it had the extra **s** on the end)

redirects to 

https://github.com/CliffCloud/Leaflet.EasyButton (current name)


Has `L.EasyButton`'s bower presence been troublesome?

**Comment by atstp** [comment]
perhaps unnecessary, but did you `bower uninstall L.EasyButton`?

**Comment by MarkAPhillips** [comment]
Hi its on the build server there is an issue and intermittently locally, running the above though seem to fix it.
Thanks.

**Comment by MarkAPhillips** [comment]
so for anyone else having this issue:

```
bower cache clean
bower uninstall L.EasyButton
bower install Leaflet.EasyButton 
``
 seems to fix it
