### ISSUE TITLE
Bower Package Name

### ISSUE THREAD

**Issue by atstp** [CliffCloud/Leaflet.EasyButton#26]
[Browsing](http://bower.io/search/?q=leaflet) [Bower](http://bower.io/search/?q=jquery) makes it look like people (myself included) are pretty bad about following bower's package naming convention, even among leaflet-specific plugins.   

@MarkAPhillips, It looks like you're the user here with the most bower experience; would you prefer the package to be named `leaflet-easybutton` or `leaflet.easybutton`?

Thanks!

**Comment by atstp** [comment]
seems like the [angular community](http://bower.io/search/?q=angular) is pretty good about using slug-style mentioned in bower's docs

**Comment by MarkAPhillips** [comment]
Thing is in leaflet they tend to follow the . rather than slug style 

e.g.

```
leaflet.fullscreen
leaflet.markercluster
leaflet.draw
```
 but have seen the slug style in other leaflet plugins also
