### ISSUE TITLE
Add Title to Button

### ISSUE THREAD

**Issue by MarkAPhillips** [CliffCloud/Leaflet.EasyButton#27]
Hi previously you could add a title to the button so when someone hovers over it you can see what it is - can this be added back in or explain how this can be done . I see it can be done using the states array but seems a bit of an overkill is you just want a simple  button with title and are not interested in state changes.
Any thoughts or is states the way to go - thanks

**Comment by atstp** [comment]
You're right, it should absolutely be there.  I just fixed it; now it's back closer to v0, just send it in as the third argument:

    L.easyButton('fa-thumbs-up', function(btn, map){
      // button actions
    }, 'title for the button');
