### ISSUE TITLE
Missing leaflet dependency?

### ISSUE THREAD

**Issue by restani** [CliffCloud/Leaflet.EasyButton#28]
In the bower.json file, I think a 

"dependencies": {
    "leaflet": "~0.7.3"
}

Block is missing. This caused me a problem because bower was loading EasyButton first, and crashed because leaflet was not loaded before.

**Comment by atstp** [comment]
That should do it, thanks!

**Comment by restani** [comment]
Great! You're just missing a comma after the closing bracket :)

**Comment by atstp** [comment]
Ah, of course.  Just fixed it and bumped the version, it should be all good now!
