### ISSUE TITLE
Setting height, width and background color of EasyButtons

### ISSUE THREAD

**Issue by adriennn** [CliffCloud/Leaflet.EasyButton#31]
Would it make sense to be able to set a custom style upon creation of an EasyButton the same way it is done [here](http://www.coffeegnome.net/control-button-leaflet/) (i.e width, height, background image & color)? From what I tried, I wasn't able to set the style for a single element only in the leaflet-bar.

**Comment by atstp** [comment]
Yeah! depending on what you're shooting for specifically, the code below should help!

`container

if there's anything that isn't clear, let me know and i'll be more specific.

### stylesheet styling

this js:

    var map = L.map('map', {}).setView([37.8, -96], 4);
    L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);

    var toggle = L.easyButton({
        id: 'toggle-check-and-x',
        states: [{
            icon: '&check;',
            stateName: 'check-mark',
            onClick: function(btn,map) {
                btn.state('x-mark');
            },
            title: 'yessssssssss'
        }, {
            icon: '&cross;',
            stateName: 'x-mark',
            onClick: function(btn,map) {
                btn.state('check-mark');
            },
            title: 'nooooooooooo'
        }]
    });
    toggle.addTo(map);

would let you target the elements with these styles

    #toggle-check-and-x{
        width: 200px;
        height: 100px;
        transition-duration: .3s;
        }
        #toggle-check-and-x.x-mark-active{
            background-color: red;
            }
        #toggle-check-and-x.check-mark-active{
            background-color: green;
            }

### inline styling

If you're wanting inline styles, (as it seems more and more people are) the same effect could be gained with this:

    var map = L.map('map', {}).setView([37.8, -96], 4);
    L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);

    var toggle = L.easyButton({
        id: 'toggle-check-and-x',
        states: [{
            icon: '<big>&check;</big>',
            stateName: 'check-mark',
            onClick: function(btn,map) {
                btn.button.style.backgroundColor = 'red';
                btn.state('x-mark');
            },
            title: 'yessssssssss'
        }, {
            icon: '<big>&cross;</big>',
            stateName: 'x-mark',
            onClick: function(btn,map) {
                btn.button.style.backgroundColor = 'green';
                btn.state('check-mark');
            },
            title: 'nooooooooooo'
        }]
    });

    toggle.button.style.width = '200px';
    toggle.button.style.height = '100px';
    toggle.button.style.backgroundColor = 'green'; // repeated line (note below)
    toggle.button.style.transitionDuration = '.3s';

    toggle.addTo(map);

if you're gonna be doing a lot of styling, you might want a function for setting each state's styles (or at least the first state) so you don't end up repeating yourself &mdash; like i did with the green background.

Hope it helps!

**Comment by adriennn** [comment]
@atstp thank you, I didn't know it was possible to set the button id, that's all I needed!

``` 
var toggle = L.easyButton({
 id: 'toggle-check-and-x',
...
```
