### ISSUE TITLE
Is title only for state based buttons?

### ISSUE THREAD

**Issue by ipepe** [CliffCloud/Leaflet.EasyButton#37]
I saw that You can set title as tool tip of button but examples only show that is it available only in buttons with many states. Can I have a button with title in default behavior?

**Comment by atstp** [comment]
Yep! if you're using just a single state, your code will look something like this:

    L.easyButton('fa-thumbs-up', function(btn, map){
      // do something here
    }, 'title for your button');

**Comment by ipepe** [comment]
Thanks. You can close it now.
