### ISSUE TITLE
tooltip

### ISSUE THREAD

**Issue by under-score** [CliffCloud/Leaflet.EasyButton#39]
how could I add one?

**Comment by atstp** [comment]
what do you mean by tooltip?  

  * using html's global [`title`](http://www.w3schools.com/tags/att_global_title.asp) attribute? (text that shows up when you hover)
  * using the `::before` or `::after` pseudo selectors? (you'd get a simple, semi-stylable element)
  * a full blown html tooltip? (a la [qtip](http://qtip2.com/) or [tether](http://tether.io/))

**Comment by under-score** [comment]
> Am 14.03.2016 um 18:16 schrieb atstp <notifications@github.com>:
> what do you mean by tooltip?

mouseover event triggers a hint: https://en.wikipedia.org/wiki/Tooltip

**Comment by atstp** [comment]
ah great, that one's built in:

    L.easyButton('your-icon', function(btn, map){
        // do something
    }, 'the tooltip for the button goes here');  

This should do the trick; let me know if it works out for you!

**Comment by under-score** [comment]
> Am 14.03.2016 um 20:09 schrieb atstp <notifications@github.com>:
> 
> ah great, that one's built in:

super, thank you, already works => https://wjst.de/gpx

**Comment by atstp** [comment]
glad to hear it!

**Comment by jasvades** [comment]
this doesn't seem to work for me... Has it been descoped recently ?
