### ISSUE TITLE
Button size

### ISSUE THREAD

**Issue by Greenbald** [CliffCloud/Leaflet.EasyButton#40]
There is an easy way to change the button size?

Thanks.

**Comment by atstp** [comment]
yeah, absolutely.  Depending on your preferences/needs there are a few approaches.

## target the whole class through css

you can generically target them with the selector `.leaflet-bar button`.  Here's a snippet from the [source](https://github.com/CliffCloud/Leaflet.EasyButton/blob/100e583328601083e8f8f461d148f356f75ea8be/src/easy-button.css#L1-L13)

    .leaflet-bar button {
      height: 26px; /* easyButton's height default */
      width: 26px;  /*  easyButton's width default */
    }

## target one button through css

to get more specific, you can specify an id for your button when you instantiate a button

```
L.easyButton( 'icon-details', function(){
  // click event here
}, 'hover text', 'YOUR-BUTTON-ID');
```

    #YOUR-BUTTON-ID {
      height: 26px; 
      width: 26px;  
    }


## target one button through js

and finally, if you want to do everything through Javascript, your button's literal `button` element is available under `easyButtonInstance.button`

```
let easyButtonInstance = L.easyButton( 'icon-details', function(){
  // click event here
}, 'hover text', 'YOUR-BUTTON-ID');

easyButtonInstance.button.style.width = '50px';
```

**Comment by geotheory** [comment]
Is the `.leaflet-bar button` approach still valid?  For me the button resizes but the icon itself does not. Similarly `span.fa  { height: 50px !important; width: 50px !important; }` resizes the span but not actual icon.

**Comment by atstp** [comment]
Most (all?) icon libraries do not scale the icon to fit the container (which is what `width` and `height` will target). 

To target the content, you can try adjusting the `font-size` and maybe `line-height` of your button. I've had luck with that in the past.

If that doesn't have the desired effect, please share some code examples along with the versions of the relevant libraries that you're using.

**Comment by geotheory** [comment]
Ah rookie error!  This works nicely `.leaflet-bar button { height: 50px !important; width: 50px !important; font-size: 2.6em; padding: 8px; }`.  Thanks.
