### ISSUE TITLE
Animating states not working.

### ISSUE THREAD

**Issue by balciseri** [CliffCloud/Leaflet.EasyButton#41]
http://danielmontague.com/projects/easyButton.js/v1/examples/#animating-states

I did as the tutorial is explaining but the animation doesn't work prorperly in any browser.
After you click on the button the image is scaling to 0 but the next image isn't scaling to 1 to take his place, more exactly after further investigations the second image is scaling to 1 but the position is wrong.

To fix it i had to comment the position
```
 .easy-button-button .button-state{
  display: block;
  width: 100%;
  height: 100%;
  /*position: relative;*/
}
```
in easy-button.css

But if you comment this line the images in the button are no more in the center and so are ugly to see : http://puu.sh/nR0hB/90fc32dcaa.jpg

**Comment by balciseri** [comment]
More infos:
here is the code : `var animatedToggle = L.easyButton({
        id: 'animated-marker-toggle',
        type: 'animate',
        states: [{
            stateName: 'add-markers',
            icon: '<span class="star">&starf;</span>',
            title: 'add some markers',
            onClick: function (control) {
                map.addLayer(randomMarkers);
                control.state('remove-markers');
            }
        }, 
            stateName: 'remove-markers',
            title: 'remove markers',
            icon: '<span class="rec">&telrec;</span>',
            onClick: function (control) {
                map.removeLayer(randomMarkers);
                control.state('add-markers');
            }
        }]
    });
    animatedToggle.addTo(map);`

and the css:

```
.leaflet-bar button,
.leaflet-bar button:hover {
  background-color: #fff;
  border: none;
  border-bottom: 1px solid #ccc;
  width: 26px;
  height: 26px;
  line-height: 26px;
  display: block;
  text-align: center;
  text-decoration: none;
  color: black;
}

.leaflet-bar button {
  background-position: 50% 50%;
  background-repeat: no-repeat;
  overflow: hidden;
  display: block;
}

.leaflet-bar button:hover {
  background-color: #f4f4f4;
}

.leaflet-bar button:first-of-type {
  border-top-left-radius: 4px;
  border-top-right-radius: 4px;
}

.leaflet-bar button:last-of-type {
  border-bottom-left-radius: 4px;
  border-bottom-right-radius: 4px;
  border-bottom: none;
}

.leaflet-bar.disabled,
.leaflet-bar button.disabled {
  cursor: default;
  pointer-events: none;
  opacity: .4;
}

.easy-button-button .button-state{
  display: block;
  width: 100%;
  height: 100%;
  /*position: relative;*/
}


.leaflet-touch .leaflet-bar button {
  width: 30px;
  height: 30px;
  line-height: 30px;
}
```

**Comment by atstp** [comment]
Yikes, my apologies. that shouldn't be the case.  

With the unedited source, adding and these lines to your code should fix the problem:

      button.easy-button-button {
        position: relative; }
      .easy-button-button .button-state {
        position: absolute;
        top: 0;
        left: 0; }

Let me know if any other issues crop up, thanks!

**Comment by balciseri** [comment]
hi, thank you.
I edited the css file adding at the bottom your code.
It seems to work!
I don't know css very well yes, so i was wondering is that a typo 
`button.easy-button-button {`
or it's correct? anyway it seems to work so thanks!


```
.leaflet-bar button,
.leaflet-bar button:hover {
    background-color: #fff;
    border: none;
    border-bottom: 1px solid #ccc;
    width: 26px;
    height: 26px;
    line-height: 26px;
    display: block;
    text-align: center;
    text-decoration: none;
    color: black;
}

.leaflet-bar button {
    background-position: 50% 50%;
    background-repeat: no-repeat;
    overflow: hidden;
    display: block;
}

    .leaflet-bar button:hover {
        background-color: #f4f4f4;
    }

    .leaflet-bar button:first-of-type {
        border-top-left-radius: 4px;
        border-top-right-radius: 4px;
    }

    .leaflet-bar button:last-of-type {
        border-bottom-left-radius: 4px;
        border-bottom-right-radius: 4px;
        border-bottom: none;
    }

.leaflet-bar.disabled,
.leaflet-bar button.disabled {
  cursor: default;
  pointer-events: none;
  opacity: .4;
}

.easy-button-button .button-state {
    display: block;
    width: 100%;
    height: 100%;
    position: relative;
}

.leaflet-touch .leaflet-bar button {
    width: 30px;
    height: 30px;
    line-height: 30px;
}

button.easy-button-button {
    position: relative;
 }
  .easy-button-button .button-state {
    position: absolute;
    top: 0;
    left: 0;
 }

```

**Comment by atstp** [comment]
I'm glad it worked out!

The selector's written correctly; it's selecting a `button` element _with_ the class `easy-button-button`.  Usually it's needlessly precise, but that should work with any older versions of EasyButton.

but code makes a better description than english:

```html
<style>

   /* `button` touches `.easy-button-button` */
   button.easy-button-button { /* styles */ }

</style>

<!-- so it targets one element that matches both -->
<button class="easy-button-button">...</button> 
```

good luck, I hope it helps!

**Comment by balciseri** [comment]
great!
Now i understand it better.
Awesome work

**Comment by dshakya** [comment]
The solution worked for me too but just wondering if this should work out of the box without having to put additional CSS.

I am using the latest version from : https://unpkg.com/leaflet-easybutton@2.0.0/src/easy-button.css
