### ISSUE TITLE
Hide button

### ISSUE THREAD

**Issue by sylvainar** [CliffCloud/Leaflet.EasyButton#43]
Hey !

First, thanks for you work ;)

Is it possible to hide a button after we placed it on the map ? And to make it reappears after ?

Thanks !

**Comment by atstp** [comment]
Glad to hear it's helping you :+1:  

And yeah, it's absolutely possible to hide/show buttons. 

It boils down to the EasyButton's `enable` and `disable` methods that will add and remove the `disabled` css class from the button.  You can get fancy with it, but most simply, you'd set 
a `.disabled` button's `display` to `none` like this:

    /* css */
    .easy-button-button.disabled {
      display: none;
    }

and 
 
    /* js */
    var myButton = L.easyButton( /* button config */ );

    myButton.disable();
    myButton.enable(); 

Here are a [few examples](http://danielmontague.com/projects/easyButton.js/v1/examples/#disabling-buttons)

Let me know if this works out for you!

**Comment by sylvainar** [comment]
Nice, it works perfectly! Thanks for the quick answer!
