### ISSUE TITLE
Supported leaflet versions

### ISSUE THREAD

**Issue by jekuno** [CliffCloud/Leaflet.EasyButton#50]
The `bower.json` and `package.json` files define Leaflet 0.7 as a depencency (BTW having two different version identifiers). As the release of Leaflet 1.0 is nearly final now:
Maybe you could add a note to the README which leaflet versions currently are supported by your plugin. That would help users who plan to update from Leaflet 0.7.x to 1.0

**Comment by atstp** [comment]
I just released `2.0.0` which bumped the leaflet dependency to 1.x.  I'll add a note in the readme in just a minute

**Comment by atstp** [comment]
It should be good to go!

**Comment by jekuno** [comment]
Thanks! Nice :)
