### ISSUE TITLE
<div> button

### ISSUE THREAD

**Issue by vdemin** [CliffCloud/Leaflet.EasyButton#52]
I want to put inside EasyButton a checkboxes or, for example, span block binded with bootstrap-daterangepicker. But I'm facing the issue under Firefox, when events doesn't go inside a button element:
https://jsfiddle.net/evxz483h/2/

Can you add an option which would allow to create button with `div` tag instead of `button`?
Or don't need to complicate EasyButton, and the better way is creating my own fork?

**Comment by atstp** [comment]
Just pushed up a commit that should help you out.

now when you're making an easyButton, you can pass a `tagName` in the options.  

the first option for the readme would then look like this:

```
var helloPopup = L.popup().setContent('Hello World!');

L.easyButton('fa-globe', function(btn, map){
    helloPopup.setLatLng(map.getCenter()).openOn(map);
}, {tagName: 'div'}).addTo( YOUR_LEAFLET_MAP ); // probably just `map`
```

you might also want to specify `leafletClasses: false` and/or `id: 'divId'` so you can apply your own styles.
