### ISSUE TITLE
Release tagName feature

### ISSUE THREAD

**Issue by jekuno** [CliffCloud/Leaflet.EasyButton#54]
You have a new `tagName` option to set the button's tag name in master which is nice.
Can you make a new release which contains this feature?

**Comment by atstp** [comment]
Thanks, that should have been done a while ago.

**Comment by jekuno** [comment]
That was really fast. :)
Could you release a v1.3.2 as well which contains the `tagName` feature for users of Leaflet 0.7.x (like me).

**Comment by atstp** [comment]
Okay, it's up at `1.3.2` :+1:

**Comment by jekuno** [comment]
Nice. Thanks :)
Made a minor update in #55
