### ISSUE TITLE
animating icon on states not showing on click

### ISSUE THREAD

**Issue by Asterrea** [CliffCloud/Leaflet.EasyButton#56]
I'm not sure if this is a problem that anyone has encountered but since I followed the same code from the example I thought it should not have a problem. I hope anyone could tell me what's wrong in my code below.

I tested out individual icons in separate easy buttons and it's valid. But using them in states, only the first (default icon) would show up. Upon clicking it to transition to the next state, the icon of that state does not show up.

```
 var animatedToggle = L.easyButton({
              id: 'animated-marker-toggle',
              type: 'animate',
              states: [{
                stateName: 'default-map',
                title: 'Default map',
                icon: 'fa fa-files-o',
                onClick: function(control) {
                  //remove side-by-side
                  control.state('trigger-side-by-side');
                }
              },{
                stateName: 'trigger-side-by-side',
                title: 'Network map',
                icon: 'fa fa-file-o',
                onClick: function(control) {
                  //add side-by-side control
                  control.state('default-map');
                }
              }]
            });
            animatedToggle.addTo(map);
```

**Comment by atstp** [comment]
On first glance, `type: 'animate'` looks like the culprit. At least assuming that you haven't added any custom css. 

If that doesn't fix it let me know and i'll take a closer look!
