### ISSUE TITLE
Link to button

### ISSUE THREAD

**Issue by Naturtecnica** [CliffCloud/Leaflet.EasyButton#58]
Hi Cliff,
how can I create a "link to" button using Leaflet.Easy.Button?
Thanx.

Lorenzo

**Comment by atstp** [comment]
Do you mean to change the window's location like `<a href="..."` would?

If that's the case, you can use javascript's `window.location.href` from inside you button's onclick function:

```
L.easyButton('fa-link', function(){
  window.location.href = "https://www.google.com/";
}).addTo(map);
```

**Comment by Naturtecnica** [comment]
Great, it works!!!
Thanx Atstp!

Lorenzo
