### ISSUE TITLE
Request to add EasyButton on cdn.js

### ISSUE THREAD

**Issue by davidtgq** [CliffCloud/Leaflet.EasyButton#59]
Hi, I submitted a request to add EasyButton on cdn.js

https://github.com/cdnjs/cdnjs/pull/10741

I don't entirely know what I'm doing, hopefully it looks about right. If not, please feel free to delete/modify it.

**Comment by atstp** [comment]
Looks like it was successfully merged, so I'm closing the issue.  Let me know if there's anything else you need.
