### ISSUE TITLE
Removing the button again

### ISSUE THREAD

**Issue by manuschiller** [CliffCloud/Leaflet.EasyButton#60]
Thanks for your plugin, it works like a charm!
What would be the best way to remove the button during runtime again?

**Comment by kaio328** [comment]
Hey,

im also very interested in this.

`EasyButton.remove();`   leads to `TypeError: this._map is null  easy-button.js:160:7`

**Comment by atstp** [comment]
How did you create and attach the `EasyButton` that you're trying to remove?

**Comment by kaio328** [comment]
This is my simplified code:
`var myButton = L.easyButton('fa fa-times', function(){
//all my stuff
	myButton.remove();
	});`

Actually everything works but firefox console fires `TypeError: this._map is null easy-button.js:160:7`

**Comment by atstp** [comment]
Okay, it's fixed with `2.1.0`

Let me know if you have any more trouble

**Comment by kaio328** [comment]
I tried the new version. Result:  `TypeError: this.removeFrom is not a function    easy-button.js:306:7`

How to remove a button now?

**Comment by atstp** [comment]
@kaio328, could you give it another go with v2.2.0?

**Comment by kaio328** [comment]
Just tried it. Everything works fine. Thank you!
