### ISSUE TITLE
Add type="button" to button HTML

### ISSUE THREAD

**Issue by nahgrin** [CliffCloud/Leaflet.EasyButton#61]
We ran into an issue recently which seems to stem from the fact that the button element does not have the attribute type="button" on it.  The problem this is causing is that an input elsewhere on the page will attempt to click on the easy button when a user focuses on the input and presses enter.

I believe this issue is related to: http://stackoverflow.com/questions/12325066/button-click-event-fires-when-pressing-enter-key-in-different-input-no-forms.

**Comment by atstp** [comment]
thanks, it should be fixed with `2.1.1`
