### ISSUE TITLE
Control.state

### ISSUE THREAD

**Issue by kaio328** [CliffCloud/Leaflet.EasyButton#62]
Hey,

how to refer to `control.state` of other buttons?

For example if you have two buttons: `buttonA` & `buttonB`:

how to set the `control.state` of `buttonB` via `buttonA`?

**Comment by atstp** [comment]
each state has as `stateName`, With that you can call the button's `state` method to set the state.

from the examples in the readme: 

```
var stateChangingButton = L.easyButton({
    states: [{
            stateName: 'zoom-to-forest',                 // with this
            icon:      'fa-tree',               
            title:     'zoom to a forest',     
            onClick: function(btn, map) {      
                map.setView([46.25,-121.8],10);
                btn.state('zoom-to-school');  
            }
        }, {
            stateName: 'zoom-to-school',                 // or this
            icon:      'fa-university',
            title:     'zoom to a school',
            onClick: function(btn, map) {
                map.setView([42.3748204,-71.1161913],16);
                btn.state('zoom-to-forest');
            }
    }]
});

stateChangingButton.addTo( YOUR_LEAFLET_MAP );
```

you can do:

```
stateChangingButton.state('zoom-to-forest');             // call like this
```

here's the relevant snippet [from the source](https://github.com/CliffCloud/Leaflet.EasyButton/blob/master/src/easy-button.js#L218-L232)

**Comment by kaio328** [comment]
worked fine! thanks!

**Comment by apdevelop** [comment]
How can I _get_ current button state, except reading private field `_currentState.stateName` ?

**Comment by StefanBrand** [comment]
For reference: Someone asked the same on gis.stackexchange.com. Here is the link: https://gis.stackexchange.com/q/307490/122597
