### ISSUE TITLE
Version 1.3.x release with TypeScript definitions

### ISSUE THREAD

**Issue by mkasprz** [CliffCloud/Leaflet.EasyButton#68]
Could You create a release of version 1.3.x, which is compatible with Leaflet 0.7.x, with TypeScript definitions? That could be very helpful.
Thank You in advance.

**Comment by atstp** [comment]
Last I checked, EasyButton's `1.3.x` should be compatible with Leaflet's `0.7.x`.  If there's an issue with that, let me know and I'll tend to it in short order 👍 

Adding the type definitions however, is outside the scope of the work I can put in with my own free time. That said, I'll happily merge in a pull request if you put one together!

**Comment by mkasprz** [comment]
Thank You.
What about merging the one from https://github.com/CliffCloud/Leaflet.EasyButton/commit/4b68cf2dab655b1922dccbd18aa29f1b3035353a and next commits? Is it incompatible with `1.3.x` version?
