### ISSUE TITLE
unpkg import

### ISSUE THREAD

**Issue by turner537** [CliffCloud/Leaflet.EasyButton#69]
The unpkg import is failing with a 404:
https://unpkg.com/leaflet-easybutton@2.0.0/src/easy-button.js

This works however:
https://unpkg.com/leaflet-easybutton@2.0.0

perhaps update documentation?

**Comment by MartinKolarik** [comment]
Lots of people have been complaining about *random* 404 and 503 unpkg responses recently. You can always use jsDelivr instead, which works in a similar way but is more reliable: https://cdn.jsdelivr.net/npm/leaflet-easybutton@2.0.0/src/easy-button.js
