### ISSUE TITLE
New parameter for setting custom class to the parameter

### ISSUE THREAD

**Issue by Arxi** [CliffCloud/Leaflet.EasyButton#7]
Could you please add a new parameter to the EasyButton creation? It would allow for a setting of a custom class to the <a> element of the control. 

Options in L.Control.EasyButtons would look something like this:

```javascript
options: {
    position: 'topleft',
    title: '',
    intentedIcon: 'fa-circle-o',
    customBtnClass: ''
},
```

and then in the onAdd function:

```
this.link = L.DomUtil.create('a', 'leaflet-bar-part ' + this.options.customBtnClass, container);
```

and then of course the appropriate new parameter in the L.easyButton function.

Thank you very much!

**Comment by atstp** [comment]
Implementation isn't as mentioned above, but the idea's supported in v1. Thanks for mentioning it!

Since there aren't any docs yet

This chunk of js (with v1):

```
L.easyButton('fa-circle-o your-custom-css-class', callback);
```

would generate an icon like this:

```
<!-- stuff above -->
    <span class="fa-circle-o your-custom-css-class fa fa-lg"></span>
<!-- stuff below -->
```
