### ISSUE TITLE
Angular2, Installing with NPM result in Property 'easyButton' does not exist on type 'typeof L'

### ISSUE THREAD

**Issue by TheSegfault** [CliffCloud/Leaflet.EasyButton#70]
I compared the repo and my node_modules, I don't have easy-button.d.ts.

Any suggestions ?

**Comment by atstp** [comment]
I'm not an active typescript user (paging the typescript binding author @teyc), but I'd assume a `typeof L` signature should come from the central leaflet library.  

Do you have leaflet in your deps?

**Comment by teyc** [comment]
Hi Cliff, it appears `TheSegfault` is correct. The leaflet-easybutton.d.ts somehow didn't get included in the npm package. 

@TheSegfault as a workaround you will have to download the typing file and include that in your sources. It doesn't necessarily have to be in `node_modules\leaflet-easybutton\src `, Typescript seems to be fairly competent at picking these up if the directory is specified the `sourceRoots` option.

**Comment by atstp** [comment]
thanks teyc!

`TheSegfault`, everything should work properly with the latest `leaflet-easybutton@2.2.2` from npm.
