### ISSUE TITLE
How to put an EasyButton inside a leaflet popup?

### ISSUE THREAD

**Issue by AndreasSchmid1** [CliffCloud/Leaflet.EasyButton#77]
Thank you CliffCloud for this amazing leaflet plugin!
Is it possible to add an easybutton inside a leaflet popup?

I want to create a zoom to drawing button.

Thanks for help in advance

**Comment by atstp** [comment]
EasyButton is for adding controls to a leaflet map; adding buttons to other elements is outside the scope.

You could either add a regular html button inside your popup, or add the easyButton to the map when your popup fires `popupopen` (and remove it on `popupclose`).
