### ISSUE TITLE
Leaflet.EasyButton : call of js function

### ISSUE THREAD

**Issue by walidaziz** [CliffCloud/Leaflet.EasyButton#78]
Hi,
I would like to call a method defined in my angular component class from my button.
But the following code give me an 'undefined function' for myMethodToCall.
How could i do that ?

Thanks

```javascript
initMap() { 
this.map = L.map('map');
   
L.easyButton('fa-globe', function(btn, map){
    this.myMethodToCall();
      }).addTo( this.map );
}
myMethodToCall () {
     this.map....
   // some dynamic stuff (call current GPS position and setView)
}
```

**Comment by atstp** [comment]
EasyButton rebinds `this` in the button's handler function. ([per the docs](http://danielmontague.com/projects/easyButton.js/v1/examples/#inside-functions))

try avoiding the use of `this`:

```js
initMap() { 
    var self = this;  // ADD THIS
    this.map = L.map('map');
   
    L.easyButton('fa-globe', function(btn, map){
        self.myMethodToCall();  // CALL AS self 
    }).addTo( this.map );
}
myMethodToCall () {
    // this.map....
    // some dynamic stuff (call current GPS position and setView)
}
```

if that doesn't work, share a minimal working example.

**Comment by walidaziz** [comment]
Great ! That works.
Thanks
