### ISSUE TITLE
Is it possible to have text on button

### ISSUE THREAD

**Issue by Hallam1995** [CliffCloud/Leaflet.EasyButton#80]
Instead of using an image as the icon for the button, is there a way to use text instead? I am wanting to have the names of cities displayed on the maps.

Thanks

**Comment by Hallam1995** [comment]
Had an issue with styling but now I have fixed it. Got text working.

**Comment by ghost** [comment]
how did you do that? please help me!

**Comment by dpa99c** [comment]
for reference, it's in [the examples](http://danielmontague.com/projects/easyButton.js/v2/examples/):

```javascript
L.easyButton( '<strong>Disable me</strong>', function(){
  this.disable();
}).addTo(map);
```
