### ISSUE TITLE
Having a dropdown with the buttons

### ISSUE THREAD

**Issue by Hallam1995** [CliffCloud/Leaflet.EasyButton#81]
Hi,

I have a map application with several 'jump to [city]' buttons. Is there a way I can combine these into a dropdown menu? So the user will see a 'cities' button, hover or click on it and then be presented with a list of cities.

Thanks

**Comment by atstp** [comment]
that's outside the scope of this plugin, but the [source for the easyBar](https://github.com/CliffCloud/Leaflet.EasyButton/blob/master/src/easy-button.js#L6) could be a decent jumping off point.

**Comment by hosein** [comment]
I'll put a bounty on this if it helps.  I want to give the user the ability to export the data in multiple formats, and having mutliple buttons is ugly.  A dropdown, or a fan-out (similar to drawing tools) would be ideal.
