### ISSUE TITLE
How to add button group

### ISSUE THREAD

**Issue by ridwanskaterock** [CliffCloud/Leaflet.EasyButton#82]
add button group like 
![image](https://user-images.githubusercontent.com/9270445/41862541-61987c44-78ce-11e8-81fb-40ca2c54ad73.png)

**Comment by atstp** [comment]
you can nest your buttons in an `L.easyBar`. 

here's the gist of what you'll want to do:

```
var expandButton = L.easyButton(/* button config here */);
var rightRotationButton = L.easyButton(/* button config here */);
var leftRotationButton = L.easyButton(/* button config here */);
var trashButton = L.easyButton(/* button config here */);

var editBar = L.easyBar([
    expandButton,
    rightRotationButton,
    leftRotationButton,
    trashButton,
]);

editBar.addTo(myMap);
```

for a running (but more complicated) example, you can see the [this section](http://danielmontague.com/projects/easyButton.js/v1/examples/#fancier-disable) in the docs
