### ISSUE TITLE
Vertical Position

### ISSUE THREAD

**Issue by EnxhiTopuzi** [CliffCloud/Leaflet.EasyButton#85]
Hello I am using your library in my project but I have some problems with the position of the buttons inside the easybar. I want to display them vertically and can't find a solution. Any help?

**Comment by atstp** [comment]
I assume you're seeing behavior that differs from what's shown in the docs?

can you describe the approaches you've already taken to troubleshoot? 

If you can share a minimal, running example of your issue, it will go a long ways towards getting you the answers you're looking for.

based on your description, there's not much to offer.  If you share more info, I'll do what I can to help.

**Comment by guiuprado** [comment]
Excellent project congrats. It's helping very much.
I have a similar problem and I workaround using a style at the page.
Probably it's because of many css overwrites from  thirdy parts templates.
        
.easy-button-container { width:34px; }

**Comment by guiuprado** [comment]
After looking closely the project don't have the css file.
So when I add everything start to work.

**Comment by atstp** [comment]
glad to hear it worked out for you @guiuprado.

@EnxhiTopuzi, I'm going to close this issue. If you are still having trouble then you can open a new issue and provide more information so I can better help you.
