### ISSUE TITLE
Get the current button state by method

### ISSUE THREAD

**Issue by StefanBrand** [CliffCloud/Leaflet.EasyButton#87]
> How can I _get_ current button state, except reading private field `_currentState.stateName` ?

_Originally posted by @apdevelop in https://github.com/CliffCloud/Leaflet.EasyButton/issues/62#issuecomment-375198450_

I propose to implement that `control.state()` returns the current state. What do you think?

**Comment by atstp** [comment]
Yeah, that's simple and intutive; thanks for the nudge.

It's implemented in f903381 and available as of with [`v2.4.0`](https://github.com/CliffCloud/Leaflet.EasyButton/tree/v2.4.0).
