### ISSUE TITLE
Button to external link 

### ISSUE THREAD

**Issue by mbutterz** [CliffCloud/Leaflet.EasyButton#89]
Is it possible to have a button with a text link that takes you to another URL?

So it would be something like this:

![3331B574-CED9-428C-9BAF-8AC19899ABA7](https://user-images.githubusercontent.com/47577758/59907831-e5a32d80-9403-11e9-9487-33a7860d3e1a.png)

**Comment by atstp** [comment]
Do you want it to look like the "★" button, or the "Fire Safety" button?

Regardless of styling, the behavior can be implemented using `window.location` (see [here](https://stackoverflow.com/questions/7077770/window-location-href-and-window-open-methods-in-javascript#7077808) and [here](https://developer.mozilla.org/en-US/docs/Web/API/Location)). 

a minimal implementation would look something like this:

```
L.easyButton('<span>first floor<span>', function(){
  window.location.href = 'https://www.google.com';
}).addTo(map);
```

**Comment by mbutterz** [comment]
I just want a button that can link to an external site, e.g. bbc news, so when you click on it it takes you to that site. 

But with a text label like the fire safety one I mocked up.

**Comment by atstp** [comment]
something like this should get you started:

wherever you're running your js:

```js
L.easyButton('<span id="bbc-news-button">BBC News<span>', function(){
    window.location.href = 'http://www.bbc.com/news';
}).addTo(map);
```

and your css:

```css
#bbc-news-button {
    /* style your button here */
}
```

**Comment by mbutterz** [comment]
Thanks for your help, I'll give it a go. 

Can you position the buttons anywhere on the map using the styling?

Is there a drop down menu option available in leaflet? That would also be useful!

**Comment by atstp** [comment]
Yeah, you can position your buttons with css. Leaflet has built-in classes for trivial stuff like grouping buttons in the `topleft`, `topright`, `bottomleft`, and `bottomright` ([see here](https://leafletjs.com/reference-1.5.0.html#control)).

In my experience, leaflet's controls are best suited for simple buttons. EasyButton adds about as much to leaflet's controls as possible without being awkward. 

For anything beyond simple buttons (like the dropdown you've mentioned), I've found that it's more straightforward to create a separate element (even with plain old `document.createElement`) and position it on top of the map with css. Something I do when maps need fanicer controls is use the `figure` element:

```html
<figure>
    <div id="my-map"></div>
    <figcaption>
        <!-- put your fancy controls here and use css to position them on top of the map -->
    </figcaption>
</figure>
```

Hope it helps
