### ISSUE TITLE
Font awesome icon doesn't work with React

### ISSUE THREAD

**Issue by josesaranda** [CliffCloud/Leaflet.EasyButton#92]
I have a React application. To enable Font Awesome icon i added, before use L.easyButton, `import 'font-awesome/css/font-awesome.min.css';` but it doesn't work.

It seems to be an incompatibility of Font Awesome with React. Did you try to use your library with React?

**Comment by atstp** [comment]
could you share a bit more about your situation?

some good stuff to see would be: 

- explanations of your attempts to solve this on your own
- the exact error messages you're seeing 
- a minimal, running example that shows your error ([see here](https://stackoverflow.com/help/minimal-reproducible-example))
- the versions of the various libraries you're using

**Comment by josesaranda** [comment]
Thanks for your reply. This was exactly what i did:

```js
...

import * as L from 'leaflet';
import 'leaflet-draw';
import 'leaflet-draw/dist/leaflet.draw.css';
import 'leaflet-draw/dist/leaflet.draw-src.css';
import 'leaflet-easybutton';
import 'leaflet-easybutton/src/easy-button.css';

...

L.easyButton('fa-trash',() => {
            // clear layer on new layer
            this.clearLayer(map);
}).addTo(map);
```

But it shows like corrupted icon.

**Comment by atstp** [comment]
is font awesome installed and imported?

**Comment by josesaranda** [comment]
Yes and yes

**Comment by atstp** [comment]
gotcha.  

Did you check the existing issues?

there's [this one](https://github.com/CliffCloud/Leaflet.EasyButton/issues/76) that mentions some issues with recent versions of Font Awesome.  Does that issue line up with your experience?

**Comment by josesaranda** [comment]
Yes is the same issue!
